name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.1.3, 3.0.5]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Bundle
        run: |
          sudo apt update
          sudo apt install -y libsqlite3-dev
          bundle install
      - name: Yarn
        run: ./bin/rails yarn:install
      - name: Rspec
        run: bundle exec rspec
