name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version-file: .ruby-version
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: bundle exec rspec
